// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXTlZiXedmvNEck4q4TbQ-oNMVcYvkOoI',
    appId: '1:445618584190:web:c8f811fef7b7ed2e22f62f',
    messagingSenderId: '445618584190',
    projectId: 'movie-review-app-7e6c5',
    authDomain: 'movie-review-app-7e6c5.firebaseapp.com',
    storageBucket: 'movie-review-app-7e6c5.firebasestorage.app',
    measurementId: 'G-BTSEHF8HPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQpALB6NA7bdTw1AEDuBU8aRh2MUkoCE',
    appId: '1:445618584190:android:02e206ab6ddaf42a22f62f',
    messagingSenderId: '445618584190',
    projectId: 'movie-review-app-7e6c5',
    storageBucket: 'movie-review-app-7e6c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfrN3UexeY-t747xKSdRYQuuR2S0zN4c',
    appId: '1:445618584190:ios:83fd71e1351cacc122f62f',
    messagingSenderId: '445618584190',
    projectId: 'movie-review-app-7e6c5',
    storageBucket: 'movie-review-app-7e6c5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfrN3UexeY-t747xKSdRYQuuR2S0zN4c',
    appId: '1:445618584190:ios:83fd71e1351cacc122f62f',
    messagingSenderId: '445618584190',
    projectId: 'movie-review-app-7e6c5',
    storageBucket: 'movie-review-app-7e6c5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXTlZiXedmvNEck4q4TbQ-oNMVcYvkOoI',
    appId: '1:445618584190:web:331ed4c43878903122f62f',
    messagingSenderId: '445618584190',
    projectId: 'movie-review-app-7e6c5',
    authDomain: 'movie-review-app-7e6c5.firebaseapp.com',
    storageBucket: 'movie-review-app-7e6c5.firebasestorage.app',
    measurementId: 'G-QXHFSGYL7W',
  );
}
